[versions]
activity = "1.9.3"
appcompat = "1.7.0"
autonomousappsSorting = "0.14"
autonomousappsUnused = "2.7.0"
constraintlayout = "2.2.0"
detektPlugin = "1.23.7"
gradlePlugin = "8.2.2"
guava = "33.4.0-jre"
ipaddress = "5.5.1"
java = "17"
junit = "4.13.2"
junitTest = "1.2.1"
koin = "4.0.0"
kotlin = "1.9.24"
ksp = "2.0.20-1.0.25"
lombock = "1.18.36"
material = "1.12.0"
monitor = "1.7.2"
okhttp = "4.12.0"
protobuf = "4.26.1"
protobufPlugin = "0.9.4"
roomRuntime = "2.6.1"

[libraries]
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "gradlePlugin" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitTest" }
androidx-monitor = { group = "androidx.test", name = "monitor", version.ref = "monitor" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-guava = { module = "androidx.room:room-guava", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detektPlugin" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
ipaddress = { module = "com.github.seancfoley:ipaddress", version.ref = "ipaddress" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-viewmodel = { group = "io.insert-koin", name = "koin-androidx-viewmodel", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-test-junit4 = { group = "io.insert-koin", name = "koin-test-junit4", version.ref = "koin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
lombock = { group = "org.projectlombok", name = "lombok", version.ref = "lombock" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }

[plugins]
deps-sorting = { id = "com.squareup.sort-dependencies", version.ref = "autonomousappsSorting" }
deps-unused = { id = "com.autonomousapps.dependency-analysis", version.ref = "autonomousappsUnused" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }

